services:
    db:
        image: docker.io/postgres
        container_name: ca_ching_postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ca_ching
        ports:
            - "5432:5432"
        volumes:
            - ./postgres:/var/lib/postgresql/data
volumes:
    db:
        driver: local
